
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

a=[1,1]

for n in xrange(33):
    x=a[-1]
    y=a[-2]
    z=x+y
    a.append(z)
xyz=sum(o for o in a if o%2==0 and o < 4000000)
print('sum of fib numbers, with the largest being less than 4m is ' + str(xyz))